name: simple_gradient_text
description: Create fast and simple gradient texts, whether linear or radial, you just decide the colors and the text to display, very easy.
version: 1.2.4
repository: https://github.com/astudilloalex/flutter_gradient_text 

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
